spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/ecc?useSSL=false&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: damiankk
    password: $cy7Pro8l3m
    initialization-mode: always

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    show-sql: false

server:
  port: 8080

---
spring:
  profiles: dev

ecc:
  security:
    jwt-secret: bezKoderSecretKey
    jwt-expiration-ms: 300000

---
spring:
  profiles: prod

