spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/ecc?useSSL=false&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: damiankk
    password: $cy7Pro8l3m
    initialization-mode: always

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    show-sql: false

server:
  port: 8080

ecc:
  company-service:
    sources:
      gpw:
        url: https://www.gpw.pl/
      nc:
        url: https://newconnect.pl/

---
spring:
  profiles: dev

ecc:
  security:
    jwt-secret: bezKoderSecretKey
    jwt-expiration-ms: 300000
  company-service:
    selenium:
      webdriver:
        name: webdriver.chrome.driver
        url: C:\\Users\\damia\\Downloads\\chromedriver_win32\\chromedriver.exe

---
spring:
  profiles: prod

